# This is a basic workflow to help you get started with Actions

name: Control Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  #push:
  #    branches:
  #      - develop
  #      - main
  #      - QA-Cypress

  pull_request:
    branches:
      - develop
      - main
      - QA-Cypress

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Primary-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
          pip install pytest
      - name: Unit tests
        run: python -m pytest testModels
        working-directory: api
      - name: Integration tests
        run: python -m pytest testREST
        working-directory: api
